name: Laravel

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1.6'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Setup Project
      run: |
          php artisan config:clear
          php artisan cache:clear
          php artisan key:generate
    - name: Directory Permissions
      run: chmod 755 -R storage bootstrap/cache
    - name: Run laravel database migrations
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: restful_api
      run: php artisan migrate
    - name: Run unit tests via PHPUnit
      env:
        DB_CONNECTION: mysql
        DB_DATABASE: restful_api
      run: ./vendor/bin/phpunit
